apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: koalatech-backend-services
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - staging
  selector:
    matchLabels:
      monitoring: koalatech
  endpoints:
    - port: http
      path: /metrics
      interval: 30s